package net.web.app.senior.dal.entity;
// Generated Feb 3, 2020 1:56:25 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ConsumerAddress generated by hbm2java
 */
@Entity
@Table(name="consumer_address"
    ,catalog="senior_app"
)
public class ConsumerAddressEntity  implements java.io.Serializable {


     private Integer id;
     private AreaEntity area;
     private ConsumerEntity consumer;
     private String street;
     private String building;
     private String floor;
     private String flat;
     private String landmark;
     private BigDecimal lat;
     private BigDecimal lng;
     private String label;
     private byte active;
     private Set<OrderEntity> orders = new HashSet<OrderEntity>(0);

    public ConsumerAddressEntity() {
    }

	
    public ConsumerAddressEntity(AreaEntity area, ConsumerEntity consumer, String street, String building, String floor, String flat, byte active) {
        this.area = area;
        this.consumer = consumer;
        this.street = street;
        this.building = building;
        this.floor = floor;
        this.flat = flat;
        this.active = active;
    }
    public ConsumerAddressEntity(AreaEntity area, ConsumerEntity consumer, String street, String building, String floor, String flat, String landmark, BigDecimal lat, BigDecimal lng, String label, byte active, Set<OrderEntity> orders) {
       this.area = area;
       this.consumer = consumer;
       this.street = street;
       this.building = building;
       this.floor = floor;
       this.flat = flat;
       this.landmark = landmark;
       this.lat = lat;
       this.lng = lng;
       this.label = label;
       this.active = active;
       this.orders = orders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="area_id", nullable=false)
    public AreaEntity getArea() {
        return this.area;
    }
    
    public void setArea(AreaEntity area) {
        this.area = area;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="consumer_id", nullable=false)
    public ConsumerEntity getConsumer() {
        return this.consumer;
    }
    
    public void setConsumer(ConsumerEntity consumer) {
        this.consumer = consumer;
    }

    
    @Column(name="street", nullable=false, length=100)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="building", nullable=false, length=100)
    public String getBuilding() {
        return this.building;
    }
    
    public void setBuilding(String building) {
        this.building = building;
    }

    
    @Column(name="floor", nullable=false, length=100)
    public String getFloor() {
        return this.floor;
    }
    
    public void setFloor(String floor) {
        this.floor = floor;
    }

    
    @Column(name="flat", nullable=false, length=100)
    public String getFlat() {
        return this.flat;
    }
    
    public void setFlat(String flat) {
        this.flat = flat;
    }

    
    @Column(name="landmark")
    public String getLandmark() {
        return this.landmark;
    }
    
    public void setLandmark(String landmark) {
        this.landmark = landmark;
    }

    
    @Column(name="lat", precision=10, scale=8)
    public BigDecimal getLat() {
        return this.lat;
    }
    
    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }

    
    @Column(name="lng", precision=11, scale=8)
    public BigDecimal getLng() {
        return this.lng;
    }
    
    public void setLng(BigDecimal lng) {
        this.lng = lng;
    }

    
    @Column(name="label", length=100)
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    
    @Column(name="active", nullable=false)
    public byte getActive() {
        return this.active;
    }
    
    public void setActive(byte active) {
        this.active = active;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consumerAddress")
    public Set<OrderEntity> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<OrderEntity> orders) {
        this.orders = orders;
    }




}


