package net.web.app.senior.dal.entity;
// Generated Feb 3, 2020 1:56:25 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name="area"
    ,catalog="senior_app"
)
public class AreaEntity  implements java.io.Serializable {


     private Integer id;
     private CityEntity city;
     private String nameAr;
     private String nameEn;
     private Set<ConsumerAddressEntity> consumerAddresses = new HashSet<ConsumerAddressEntity>(0);
     private Set<DeliveryAreaEntity> deliveryAreas = new HashSet<DeliveryAreaEntity>(0);
     private Set<OrderEntity> orders = new HashSet<OrderEntity>(0);
     private Set<BranchEntity> branches = new HashSet<BranchEntity>(0);

    public AreaEntity() {
    }

	
    public AreaEntity(CityEntity city, String nameAr, String nameEn) {
        this.city = city;
        this.nameAr = nameAr;
        this.nameEn = nameEn;
    }
    public AreaEntity(CityEntity city, String nameAr, String nameEn, Set<ConsumerAddressEntity> consumerAddresses, Set<DeliveryAreaEntity> deliveryAreas, Set<OrderEntity> orders, Set<BranchEntity> branches) {
       this.city = city;
       this.nameAr = nameAr;
       this.nameEn = nameEn;
       this.consumerAddresses = consumerAddresses;
       this.deliveryAreas = deliveryAreas;
       this.orders = orders;
       this.branches = branches;
    }
   
     @Id @GeneratedValue(strategy=GenerationType.IDENTITY)  
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="city_id", nullable=false)
    public CityEntity getCity() {
        return this.city;
    }
    
    public void setCity(CityEntity city) {
        this.city = city;
    }

    
    @Column(name="name_ar", nullable=false, length=100)
    public String getNameAr() {
        return this.nameAr;
    }
    
    public void setNameAr(String nameAr) {
        this.nameAr = nameAr;
    }

    
    @Column(name="name_en", nullable=false, length=100)
    public String getNameEn() {
        return this.nameEn;
    }
    
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="area")
    public Set<ConsumerAddressEntity> getConsumerAddresses() {
        return this.consumerAddresses;
    }
    
    public void setConsumerAddresses(Set<ConsumerAddressEntity> consumerAddresses) {
        this.consumerAddresses = consumerAddresses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="area")
    public Set<DeliveryAreaEntity> getDeliveryAreas() {
        return this.deliveryAreas;
    }
    
    public void setDeliveryAreas(Set<DeliveryAreaEntity> deliveryAreas) {
        this.deliveryAreas = deliveryAreas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="area")
    public Set<OrderEntity> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<OrderEntity> orders) {
        this.orders = orders;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="area")
    public Set<BranchEntity> getBranches() {
        return this.branches;
    }
    
    public void setBranches(Set<BranchEntity> branches) {
        this.branches = branches;
    }




}


